global_latvia_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from landing import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path("signup/", views.SignUp.as_view(), name='signup'),
    path("accounts/", include('django.contrib.auth.urls')),
    path('about/',views.AboutUsView.as_view(),name='aboutus'),
    path('ourwork/',views.OurWorkView.as_view(),name='our_work'),
    path('get_involved/',views.GetInvolvedView.as_view(),name='get_involved'),
    path('stories/', views.StoriesView.as_view(), name= 'stories'),
    path('contact', views.ContactView.as_view(), name='contact'),
    path('profile/<str:username>/',views.user_profile, name='user_profile'),
    path("logout/",views.logout_view,name='logout'),
    path('fundraise/<str:username>/',views.FundraiseView.as_view(), name='fundraise')

]

landing/urls.py
from landing import views
from django.urls import path
from django.urls import re_path
from django.contrib.auth import views as auth_views
from landing.views import logout_view


app_name= 'landing'


urlpatterns  = [
    path('', views.LandingPageView.as_view(), name="landing_page"),
    path("login/", auth_views.LoginView.as_view(
        template_name='landing/login.html'
    ), name='login'),
    path("logout/",views.logout_view,name='logout'),
   # path("signup/",views.SignUp.as_view(template_name='landing/signup.html'),name='signup'),
    path("signup/", views.signup, name='signup'),
    path('activate/<uidb64>/<token>/',views.activate,name='activate'),
    path('about/', views.AboutUsView.as_view(),name='aboutus'),
    path('ourwork/', views.OurWorkView.as_view(), name='our_work'),
    path('get_involved/', views.GetInvolvedView.as_view(), name='get_involved'),
    path('stories/', views.StoriesView.as_view(), name='stories'),
    path('contact/',views.ContactView.as_view(), name='contact'),
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    path('fundraise/<str:username>/', views.FundraiseView.as_view(), name='fundraise')
]

landing/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth import get_user_model
# Create your models here.'
#
User = get_user_model() 

#class User(auth.models.User,auth.models.PermissionsMixin):

    #def __str__(self):
       # return "@{}".format(self.username)

class GenderChoice(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='gender')
    Gender_Choices = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]

    gender = models.CharField(max_length=10, choices=Gender_Choices)

class Address(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE, related_name='address',)
    #Address line 1
    address_one = models.CharField(max_length=100)
    #Address line 2
    address_two = models.CharField(max_length=100)
    #City 
    city = models.CharField(max_length=100)                 
    #Zipcode
    zipcode=models.CharField(max_length=10)
    #Country
    country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.address_one}, {self.city}, {self.zipcode},{self.country}"

landing/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Address
from .models import GenderChoice
from.countries_list import COUNTRY_CHOICES

User = get_user_model()

class CustomSignUpForm(UserCreationForm):
    first_name = forms.CharField(
         max_length=30,
          required=True,
          label='First Name',
          help_text="Enter your first name.",
          widget=forms.TextInput(attrs={'class':'first_name'})
          )
    
    last_name = forms.CharField(
         max_length=30,
           required=True,
           label="Last Name",
           help_text="Enter your last name.",
           widget=forms.TextInput(attrs={'class':'last_name'})
           )
    

    class Meta:
        fields = ('username', 'first_name', 'last_name', 'email', 'password1',  'password2')
        model = User
        labels ={
            'username': 'Username', 
        }
        help_texts  = {
            'username' : " ",
            'password1': "",
            'password2': " ",
        }

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Username'

class GenderSelect(forms.ModelForm):
    class Meta:
        model= GenderChoice
        fields= ['gender']
        widgets = {'gender': forms.RadioSelect(attrs={'class': 'gender-buttons'}),}

class HomeAddress(forms.ModelForm):
    address_one = forms.CharField(
        required = True,
        max_length = 100,
        label = "Address 1",
        widget= forms.TextInput(attrs={'class':'address1'})
    )

    address_two = forms.CharField(
        required = False,
        max_length = 100,
        label = "Address line 2",
        widget= forms.TextInput(attrs={'class':'address2'})
    )

    city = forms.CharField(
        required = True,
        max_length = 100,
        label = "City",
        widget= forms.TextInput(attrs={'class':'city'})
    )
    
    zipcode = forms.CharField(
        required = True,
        max_length = 100,
        label = "Zipcode",
        widget= forms.TextInput(attrs={'class':'zipcode'})
      
    )

    country = forms.ChoiceField(
        required = True,
        label = "Country",
        choices= [(" ", '---Please Select a Country---')] + COUNTRY_CHOICES,
        widget= forms.Select(attrs={'class':'countries', 'data-placeholder':'<--Select a Country-->'})
    )

    class Meta:
        model = Address
        fields = ['address_one', 'address_two', 'city','zipcode', 'country']
     

landing/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView, CreateView, DetailView, ListView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.urls import reverse
from . import forms
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404

from .models import Address

#user email validator libraries
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.core.mail import send_mail
from .forms import CustomSignUpForm
from .forms import HomeAddress
from .forms import GenderSelect
from django.contrib.auth import get_user_model
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_bytes





# Create your views here.

class LandingPageView(TemplateView):
    template_name = 'landing/Global_Aid_Network_Latvia_Landing.html'

class AboutUsView(TemplateView):
    template_name='landing/About_Us.html'

class OurWorkView(TemplateView):
    template_name = 'landing/Our_Work.html'

class GetInvolvedView(TemplateView):
    template_name='landing/get_involved.html'

class StoriesView(TemplateView):
    template_name = 'landing/stories.html'

class ContactView(TemplateView):
    template_name = 'landing/contact.html'

@login_required
def user_profile(request, username):
        
        user = get_object_or_404(User, username=username)
        address = getattr(user, "address",None)
        gender = getattr(user, "gender", None)

        print("PROFILE USER:", user.username)
        print("ADDRESS FOUND:", address)

        
        return render(request, "landing/user_profile.html", {"profile_user": user, "address":address, "gender": gender})




class SignUp(CreateView):
    form_class = forms.CustomSignUpForm
    success_url = reverse_lazy('login')
    template_name = 'landing/signup.html'

class FundraiseView(TemplateView, LoginRequiredMixin):
    template_name = 'landing/fundraise.html'


def signup(request):
    if request.method == "POST":
       user_form = CustomSignUpForm(request.POST)
       address_form = HomeAddress(request.POST)
       gender_form = GenderSelect(request.POST)
       if user_form.is_valid() and gender_form.is_valid() and address_form.is_valid():
            user = user_form.save(commit=False)
            user.is_active = False
            user.save() 

            gender = gender_form.save(commit=False)
            gender.user = user 
            gender.save()

            address = address_form.save(commit=False)
            address.user = user
            address.save()

            uid = urlsafe_base64_encode(force_bytes(user.pk))

            token = default_token_generator.make_token(user)
            domain = get_current_site(request).domain
            link = f"http://{domain}/activate/{uid}/{token}/"
            print("✅ Email link:", link) 
            send_mail(
                "Confirm your email",
                f"Click to verify : {link}",
                "no-reply@yourdomain.com",
                [user.email],
            )
            return render(
                request,
                "landing/email_verification_sent.html",
                {"email": user.email}
            )
           
    else:
        user_form = CustomSignUpForm()
        gender_form= GenderSelect()
        address_form = HomeAddress()

    return render(request, "landing/signup.html", {"user_form":user_form, "gender_form":gender_form, "address_form":address_form})
    #


User = get_user_model()

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except Exception:
        user=None

    if user and default_token_generator.check_token(user,token):
        user.is_active=True
        user.save()
        return render(request, "landing/email_verified.html",{"user":user})
    
    return HttpResponse ("Activation link is invalid or expired")

def logout_view(request):
    logout(request)
    print(request.session.keys())
    return redirect('landing:landing_page') 

landing/templates/landing/About_Us.html
{% extends "landing/base.html" %}
{% load static %}

{% block content  %}
{% endblock %}

landing/templates/landing/Global_Aid_Network_Latvia_Landing.html
{% extends "landing/base.html"%}
{% load static %}

{% block content %}

   <p class="special-moto"><span id="reveal">REVEALING</span> HOPE <span class="special-period">.</span> <span id="restore">RESTORING </span>LIFE<span class="special-period">.</span></p>

   

{% endblock %}

landing/templates/landing/Our_Work.html
{% extends 'landing/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href=" {% static 'css/ourwork.css' %}">
{% endblock %}

{% block content %}
<h1 class="title-align">Our Work</h1>
{% endblock %}

landing/templates/landing/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'css/global_styles.css' %}">
        <!--fontawesome icons(  later will be downloaded)-->
        <link rel="stylesheet" href="./fontawesome-free-7.1.0-web/">
  
        

        {% block head %} 
          
        {% endblock %}
    
    </head>
    <body>

    <header class="top-bar">
        <div class="logo">
          <!--global aid log (when clicked, it brings back to home pageo-->
            <img src="{% static 'images/logo-1-1.png' %}" alt="Global Aid Logo" onclick="window.location.href='{% url 'landing:landing_page' %}'">
          </div>
        <nav class="nav-links">
          
        <div class="top-links">
            {% if user.is_authenticated %}
            <button type="button" id="fundraise" onclick="window.location.href='{% url 'landing:signup' %}'">FUNDRAISE</button>
            {% else %}
            <button type="button" id="fundraise" onclick="window.location.href='{% url 'landing:signup' %}'">REGISTER</button>
            {% endif %}
            <button type="button" id="give" href="#">GIVE</button>
        </div>
        <br>
        <div class="link-item">
            <!-- Button 1 -->
            <div class="button-item">
              <div class="boxes">
                <div class="box"></div>
                <div class="box"></div>
                <div class="box"></div>
              </div>
              <button class="btn" type="button" onclick="window.location.href='{% url 'landing:our_work'%}'">OUR WORK</button>
            </div>
      
            <!-- Button 2 -->
            <div class="button-item">
              <div class="boxes">
                <div class="box"></div>
                <div class="box"></div>
                <div class="box"></div>
              </div>
              <button class="btn" type="button" onclick="window.location.href='{% url 'landing:aboutus' %}'">ABOUT</button>
            </div>
      
            <!-- Button 3 -->
            <div class="button-item">
              <div class="boxes">
                <div class="box"></div>
                <div class="box"></div>
                <div class="box"></div>
              </div>
              <button class="btn" type="button" onclick="window.location.href='{% url 'landing:get_involved' %}'">GET INVOLVED</button>
            </div>
      
            <!-- Button 4 -->
            <div class="button-item">
              <div class="boxes">
                <div class="box"></div>
                <div class="box"></div>
                <div class="box"></div>
              </div>
              <button class="btn" type="button" onclick="window.location.href='{% url 'landing:stories' %}'">STORIES</button>
            </div>
      
            <!-- Button 5 -->
            <div class="button-item">
              <div class="boxes">
                <div class="box"></div>
                <div class="box"></div>
                <div class="box"></div>
              </div>
              <button class="btn" type="button" onclick="window.location.href='{% url 'landing:contact' %}'">CONTACT</button>
            </div>

          <!--user authentication template urls-->
            {% if user.is_authenticated %}
             <div class="button-item">
              <div class="boxes">
                <div class="box"></div>
                <div class="box"></div>
                <div class="box"></div>
              </div>
              <button class="btn" type="button"onclick="window.location.href='{% url 'landing:user_profile' username=request.user.username %}'">My Profile</button>
            </div>

            <!--<div>
              <button class="btn" id="profile_btn" onclick="window.location.href='{% url 'landing:user_profile' username=request.user.username %}'">My Profile</button>
            </div> -->
            {% endif %}
          

          <!--Login and logout-->
          {% if user.is_authenticated %}
          <div class="logout">
           <li> <a id="logout_link" href="{% url 'logout' %}">LOG OUT</a></li>
          </div>
          {% else %}
           <div class="button-item">
              <div class="boxes">
                <div class="box"></div>
                <div class="box"></div>
                <div class="box"></div>
              </div>
              <button class="btn" type="button"onclick="window.location.href='{% url 'landing:login'  %}'">LOGIN</button>
            </div>

           <!-- <div class="login">
             <li> <button id="login_link" onclick="window.location.href='{% url 'landing:login'  %}'">Log In</button></li>
            </div> -->
            {% endif %}
        </div>
                          
        </nav>
    </header>
    <div class="nav-actions">

    </div>
    <p>
        {% block content %}
        {% endblock%}
        

    <script src="{% static 'js/global.js' %}"></script>
    </body>


  <footer id="bottom-bar">
    <div id="social-media-container">
      <img></img>
    </div>

    <div id="external-links-container">
      <a class="external-link" href="">Global Aid Network Worldwide</a>
      <a class="external-link" href="">Careers</a>
    </div>
  </footer>
   
</html>

landing/templates/landing/contact.html
{% extends "landing/base.html" %}
{% load static %}

{% block content %}
<h1 class="title-align">Contact Us</h1>
{% endblock %}

landing/templates/landing/email_verification_sent.html
<!DOCTYPE html>
<html>
    <head>
    </head>
<body>
    <h2>Check your email.</h2>
    <p>We sent you a verification link to {{  email  }}. Click  it to activate your account.</p>
</body>
<html>

landing/templates/landing/email_verified.html
<!DOCTYPE html>
<html>
    <head>
    </head>
<body>
<h2>Email verified ✅</h2>
<p>Your account is now active. You can <a href="/login/">log in</a>.</p>
</body>
</html>

landing/templates/landing/get_involved.html
{% extends "landing/base.html" %}
{% load static %}

{% block content %}
<h1 class="title-align"> Get involved</h1>
{% endblock %}

landing/templates/landing/login.html
    {% extends "landing/base.html" %}


    {% block content %}


    {% if user.is_authenticated %}
    Hi {{ user.username }}!
    {% else %}
    <p id="nologin">You are not logged in</p>
    {% endif %}

    <div>
        <h1>Login</h1>
        <form  class ="form-container" action="{% url 'login' %}" class="login-form" method="POST">
            {% csrf_token %}


            {{ form.as_p }}
            <input class="login_input" type="submit" value="Sign In">
            
        </form>

        {% endblock  %}

landing/templates/landing/signup.html
{% extends "landing/base.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href=" {% static 'css/signup.css' %}">
{% endblock %}

{% block content %}

{% if form.errors %}
<div id="error" style="color: red; margin-bottom: 20px;">
    <strong>There were some errors:</strong>
    {{ form.errors }}
</div>
{% endif %}

{% if not user.is_authenticated %}
<h1 class="title-align">Personal Information</h1>
<div class="signup_form_container">
    <h1 class="title-align">Sign Up</h1>
    <form class="signup_form" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}

        <h2>Your Gender</h2>
            {{gender_form.as_p}}
    <div class="address_form">
        <h2>Address<h2>
             <p>{{address_form.as_p}}</p>
        </div>
        <input class="signup_input" type="submit" value="Sign Up">
    </form>
</div>
{% else %}
<h1 class="title-align">Fundraise</h1>
{% endif %}
{% endblock %}

landing/templates/landing/stories.html
{% extends "landing/base.html" %}
{% load static %}

{% block content %}

<h1 class="title-align">Stories</h1>

{% endblock %}

landing/templates/landing/user_profile.html
{% extends 'landing/base.html' %}
{% load static %}
{% block content %}
<h1 class="title-align">{{user.first_name}}'s Profile</h1>
<br/> <h2 class="title-align">Basic Information</h2>

<p class="profile-labels">Username: {{ profile_user }}</p>
<p class="profile-labels">First name: {{ user.first_name }}</p>
<p class="profile-labels">Last name: {{ user.last_name }}</p>




<h3 class="userprofile-heading">{{user.first_name}}'s Address</h3>
<p>{{address.address_one}}</p>
{% if address.address_two %}
<p>{{address.address_two}}
{% endif %}
<p>{{ address.city }}</p>
<p>{{address.zipcode}}</p>
<p>{{address.country}}</p>

{% endblock %} -->

<!-- landing/templates/landing/user_profile.html 

<h1>{{ profile_user.username }}'s Profile</h1>

{% if gender %}
<p>Gender: {{ gender.gender }}</p>
{% else %}
<p>Gender not set</p>
{% endif %}

{% if address %}
<p>Address:</p>
<ul>
    <li>{{ address.address_one }}</li>
    <li>{{ address.address_two }}</li>
    <li>{{ address.city }}</li>
    <li>{{ address.zipcode }}</li>
    <li>{{ address.country }}</li>
</ul>
{% else %}
<p>No address on file</p>
{% endif %} -->